

import type { Metadata } from "next";
import { Providers } from "./useContext/useTheme";
import "./globals.css";
import Header from "@/app/header/page"
import Footer from "@/app/footer/page"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
let g='dark:bg-white bg-black dark:text-black text-white'
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
      >
        <Providers >
      <Header />
          <div className="mt-[5rem]">
            {children}
          </div>
          <Footer />
        </Providers>

      </body>
    </html>
  );
}
