
import type { Metadata } from "next";
import "./globals.css";
import Header from"@/app/header/page"
import Footer from "@/app/footer/page"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
        >
        <Header/>
      <div className="mt-[5rem]">
        {children}
      </div>
        <Footer/>
      </body>
    </html>
  );
}
