import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <div className="h-screen flex items-center justify-center flex-col gap-5 opacity-80 ">
      <div className="p-4 sm:w-1/3 xl:w-1/4  mx-5 sm:mx-auto h-auto -mt-20  dark:bg-gray-800 bg-gray-200 rounded-xl ">
        {children}
      </div>
    </div>
  );
}
